name: Amiga OS4

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        uses: hitman-codehq/Amiga-Build-OS4@v1
        env:
          PREFIX: ppc-amigaos-
        with:
          command: 'make'
      - name: Build Debug
        uses: hitman-codehq/Amiga-Build-OS4@v1
        env:
          PREFIX: ppc-amigaos-
        with:
          command: 'make DEBUG=1'
      - name: Archive Libraries
        uses: actions/upload-artifact@v3
        with:
          name: Amiga-Libraries-OS4
          path: |
            Debug_OS4/*.a
            Release_OS4/*.a
