name: LinuxQt

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
      - name: Build
        run: |
          qmake
          make -f Makefile
      - name: Build Debug
        run: |
          qmake
          make -f Makefile debug
      - name: Archive Libraries
        uses: actions/upload-artifact@v3
        with:
          name: Linux-Qt-Libraries
          path: |
            DebugQt/*.a
            ReleaseQt/*.a
