name: Unix

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Debug
      run: |
        make DEBUG=1
        cd Tests
        make DEBUG=1
        for file in Debug/T_*.debug; do $file; done
    - name: Build
      run: |
        make
        cd Tests
        make
        for file in Debug/T_*.debug; do $file; done
