name: Windows

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: '16.0'
      - name: Build
        run: |
          msbuild /p:Configuration=Release /p:Platform=x86
          msbuild /p:Configuration=Release /p:Platform=x64
          cd Tests
          Get-ChildItem -Path *.vcxproj | ForEach-Object {& msbuild /p:Configuration=Release /p:Platform=x86 $_.FullName}
          Get-ChildItem -Path *.vcxproj | ForEach-Object {& msbuild /p:Configuration=Release /p:Platform=x64 $_.FullName}
      - name: Build Debug
        run: |
          msbuild /p:Configuration=Debug /p:Platform=x86
          msbuild /p:Configuration=Debug /p:Platform=x64
          cd Tests
          Get-ChildItem -Path *.vcxproj | ForEach-Object {& msbuild /p:Configuration=Debug /p:Platform=x86 $_.FullName}
          Get-ChildItem -Path *.vcxproj | ForEach-Object {& msbuild /p:Configuration=Debug /p:Platform=x64 $_.FullName}
      - name: Test
        run: |
          cd Tests
          Get-ChildItem -Path Win32\Release\*.exe | ForEach-Object {& $_.FullName}
          Get-ChildItem -Path x64\Release\*.exe | ForEach-Object {& $_.FullName}
      - name: Test Debug
        run: |
          cd Tests
          Get-ChildItem -Path Win32\Debug\*.exe | ForEach-Object {& $_.FullName}
          Get-ChildItem -Path x64\Debug\*.exe | ForEach-Object {& $_.FullName}
      - name: Archive Libraries
        uses: actions/upload-artifact@v3
        with:
          name: Libraries
          path: |
            x86/Debug/*.lib
            x64/Debug/*.lib
            x86/Release/*.lib
            x64/Release/*.lib
